# Generated by Django 5.2.13 on 2026-04-24 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beat_auth', '0002_termsandconditions_usertermsacceptance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
