# Generated by Django 5.2.13 on 2026-04-24 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
        ('beat_auth', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termsandconditions',
            options={'ordering': ['-created_at'], 'verbose_name': 'Legal document', 'verbose_name_plural': 'Legal documents'},
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='application',
            field=models.ForeignKey(blank=True, help_text='Application this document belongs to. NULL = global / cross-app.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_documents', to='apps.application'),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='kind',
            field=models.CharField(choices=[('terms', 'Términos y Condiciones'), ('privacy', 'Política de Privacidad')], default='terms', max_length=20),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='version',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='termsandconditions',
            constraint=models.UniqueConstraint(fields=('application', 'kind', 'version'), name='uniq_legal_doc_app_kind_version'),
        ),
    ]
