# Generated by Django 5.2.17 on 2026-09-03 16:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat_auth', '0004_alter_termsandconditions_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOtp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_code', models.CharField(blank=True, help_text='Producto que inició el login (Application.code).', max_length=50, verbose_name='Application code')),
                ('code_hash', models.CharField(max_length=256, verbose_name='Code hash')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Attempts')),
                ('sends', models.PositiveIntegerField(default=1, verbose_name='Sends')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('used', 'Used'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Expires at')),
                ('last_sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last sent at')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Used at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Email OTP',
                'verbose_name_plural': 'Email OTPs',
                'db_table': 'auth_email_otp',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='auth_email__user_id_c21fd8_idx'), models.Index(fields=['status', 'expires_at'], name='auth_email__status_452105_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_code', models.CharField(blank=True, max_length=50, verbose_name='Application code')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Token hash')),
                ('device_name', models.CharField(blank=True, max_length=255, verbose_name='Device name')),
                ('user_agent', models.TextField(blank=True, verbose_name='User agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last used at')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Expires at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revoked at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Trusted device',
                'verbose_name_plural': 'Trusted devices',
                'db_table': 'auth_trusted_device',
                'ordering': ['-last_used_at'],
                'indexes': [models.Index(fields=['user', 'revoked_at'], name='auth_truste_user_id_8b52be_idx')],
            },
        ),
    ]
