# Generated by Django 5.2.17 on 2026-09-03 16:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat_auth', '0005_emailotp_trusteddevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushApprover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_code', models.CharField(blank=True, max_length=50, verbose_name='Application code')),
                ('delivery_ref', models.CharField(help_text='Identificador opaco que el producto usa para entregar el aviso.', max_length=255, verbose_name='Delivery reference')),
                ('device_label', models.CharField(blank=True, max_length=255, verbose_name='Device label')),
                ('platform', models.CharField(blank=True, max_length=20, verbose_name='Platform')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Last used at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revoked at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_approvers', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Push approver',
                'verbose_name_plural': 'Push approvers',
                'db_table': 'auth_push_approver',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_code', models.CharField(blank=True, max_length=50, verbose_name='Application code')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('used', 'Used')], db_index=True, default='pending', max_length=16, verbose_name='Status')),
                ('numbers', models.JSONField(default=list, verbose_name='Numbers')),
                ('expected_number', models.PositiveSmallIntegerField(verbose_name='Expected number')),
                ('device_name', models.CharField(blank=True, max_length=255, verbose_name='Device name')),
                ('user_agent', models.TextField(blank=True, verbose_name='User agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Expires at')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved at')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Used at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_approvals', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='beat_auth.pushapprover', verbose_name='Approver')),
            ],
            options={
                'verbose_name': 'Login approval',
                'verbose_name_plural': 'Login approvals',
                'db_table': 'auth_login_approval',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pushapprover',
            index=models.Index(fields=['user', 'revoked_at'], name='auth_push_a_user_id_d4794c_idx'),
        ),
        migrations.AddConstraint(
            model_name='pushapprover',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('user', 'application_code', 'delivery_ref'), name='uniq_active_push_approver'),
        ),
        migrations.AddIndex(
            model_name='loginapproval',
            index=models.Index(fields=['user', 'status'], name='auth_login__user_id_609f9f_idx'),
        ),
        migrations.AddIndex(
            model_name='loginapproval',
            index=models.Index(fields=['status', 'expires_at'], name='auth_login__status_0deba5_idx'),
        ),
    ]
