# Generated by Django 5.2.17 on 2026-09-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat_auth', '0006_pushapprover_loginapproval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_exempt',
            field=models.BooleanField(default=False, help_text='Solo para cuentas de revisión de las tiendas. Cualquier otro uso es una contraseña sola protegiendo la cuenta.', verbose_name='Exenta de segundo factor'),
        ),
    ]
