# Generated by Django 5.2.17 on 2026-09-03 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat_auth', '0007_user_mfa_exempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mfa_exempt',
        ),
        migrations.AddField(
            model_name='user',
            name='review_account_reason',
            field=models.CharField(blank=True, help_text='Ej.: revisión iOS 1.4.0', max_length=200, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='user',
            name='review_account_set_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Activada el'),
        ),
        migrations.AddField(
            model_name='user',
            name='review_account_set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Activada por'),
        ),
        migrations.AddField(
            model_name='user',
            name='review_account_until',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Mientras esta fecha esté en el futuro, la cuenta entra sin código y sin passkey. Máximo 30 días; déjalo vacío para desactivarlo.', null=True, verbose_name='Cuenta de revisión hasta'),
        ),
    ]
