# Generated by Django 5.2.15 on 2026-06-22 02:08

import django.db.models.deletion
import uuid
import webauthn_auth.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAuthnChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(db_index=True, default=webauthn_auth.models.generate_state, max_length=64, unique=True)),
                ('ceremony', models.CharField(choices=[('registration', 'Registration'), ('authentication', 'Authentication')], max_length=20)),
                ('challenge', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True, default=webauthn_auth.models.default_challenge_expiry)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'webauthn_challenge',
                'indexes': [models.Index(fields=['state', 'expires_at'], name='webauthn_ch_state_618836_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_id', models.CharField(db_index=True, max_length=512, unique=True)),
                ('public_key', models.TextField()),
                ('sign_count', models.BigIntegerField(default=0)),
                ('aaguid', models.CharField(blank=True, default='', max_length=36)),
                ('transports', models.JSONField(blank=True, default=list)),
                ('friendly_name', models.CharField(blank=True, default='', max_length=120)),
                ('backup_eligible', models.BooleanField(default=False)),
                ('backup_state', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WebAuthn Credential',
                'verbose_name_plural': 'WebAuthn Credentials',
                'db_table': 'webauthn_credential',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='webauthn_cr_user_id_c92cf1_idx')],
            },
        ),
    ]
