# Generated by Django 5.2.15 on 2026-07-17 19:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_application_code_application_enforce_app_access'),
        ('business', '0006_remove_orphan_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAppAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deleted at')),
                ('version', models.PositiveIntegerField(default=1, help_text='Record version for optimistic locking', verbose_name='Version')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about changes', verbose_name='Notes')),
                ('license_type', models.CharField(choices=[('none', 'Sin licencia'), ('trial', 'Prueba'), ('standard', 'Estándar'), ('enterprise', 'Enterprise')], default='none', help_text='«Sin licencia» bloquea el acceso de toda la empresa a este producto.', max_length=20)),
                ('is_enabled', models.BooleanField(default=True, help_text='Interruptor manual, por encima de la licencia. Desactívalo para cortar en seco el acceso aunque la licencia siga vigente.')),
                ('expires_at', models.DateField(blank=True, help_text='Pasada esta fecha la empresa queda bloqueada. Vacío = no caduca.', null=True)),
                ('max_users', models.PositiveIntegerField(default=0, help_text='Asientos contratados para este producto. 0 = no cabe nadie nuevo.')),
                ('access_notice', models.TextField(blank=True, default='', help_text='Mensaje opcional para la pantalla de bloqueo del producto.')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_accesses', to='apps.application')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_accesses', to='business.business')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Acceso a producto',
                'verbose_name_plural': 'Accesos a productos',
                'db_table': 'business_app_access',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('business', 'application'), name='uniq_business_application_active')],
            },
        ),
    ]
