# Generated by Django 5.2.15 on 2026-07-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='code',
            field=models.SlugField(blank=True, help_text="Identificador estable del producto (p.ej. 'metis', 'atlas', 'delta'). Se usa para la autorización por producto; comparar por 'code' es más robusto que por 'name'.", null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='application',
            name='enforce_app_access',
            field=models.BooleanField(default=False, help_text='Si está activo, se rechaza en el login (y en cada request) a los usuarios cuya(s) empresa(s) no tienen una licencia válida de este producto. Actívalo por producto tras hacer el backfill de accesos.', verbose_name='Enforce app access'),
        ),
    ]
