# Generated by Django 5.2.17 on 2026-09-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_populate_application_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='enforce_mfa',
            field=models.BooleanField(default=False, help_text='Si está activo, el login de este producto exige un segundo factor por correo antes de emitir tokens. Actívalo solo cuando el frontal del producto sepa manejar la respuesta de dos pasos (mfa_required + /auth/mfa/verify/).', verbose_name='Enforce MFA'),
        ),
    ]
